### ISSUE TITLE
Requesting new or editing existing emoji due to out of tune colors

### ISSUE THREAD

**Issue by D3vil0per** [seanprashad/slackmoji#21]
Hello,
I was giving a look to https://github.com/seanprashad/slackmoji/tree/master/emoji/parrots/party-stub.gif

It is possible to create a new one like that but without // TODO grey string? Because that grey color could be out of tune with the rainbow color of { }.

Thank you in advance

**Comment by seanprashad** [comment]
Hey @D3vil0per! No worries - I've updated `parrots/party-stub.gif` to not have the `TODO` comment and instead created a copy that does - `parrots/party-stub-todo.gif`. See them below:

https://github.com/seanprashad/slackmoji/blob/master/emoji/parrots/party-stub.gif

https://github.com/seanprashad/slackmoji/blob/master/emoji/parrots/party-stub-todo.gif
